version: '3.8'

services:
  api:
    image: vimagick/json-server
    volumes:
      - ./mock-api/db.json:/data/db.json
    ports:
      - "3001:3000"
    command: json-server --watch db.json --host 0.0.0.0
